<script lang="ts">
  import { brandingState } from "$state/branding.svelte";
  import { translatePeriod } from "$utils/translators";

  interface Props {
    clearanceData: {
      name: string;
      stno: string;
      period: string;
      dateIssued: string;
      refNo: string;
      branding: string;
      signatory: string;
      signatoryTitle: string;
    };
    qrDataUrl: string;
  }

  let { clearanceData, qrDataUrl }: Props = $props();

  const activeBranding = $derived(brandingState.profile);

  const now = new Date();
  const getOrdinalNum = (n: number) =>
    n + (n > 0 ? ["th", "st", "nd", "rd"][(n > 3 && n < 21) || n % 10 > 3 ? 0 : n % 10] : "");
  const day = getOrdinalNum(now.getDate());
  const month = now.toLocaleString("en-US", { month: "long" });
  const year = now.getFullYear();
</script>

<div
  id="export-template"
  class="export-font fixed top-0 left-[-10000px] flex min-h-[297mm] w-[210mm] flex-col bg-[#ffffff] text-[#000000]"
>
  <div class="w-full">
    <img src={activeBranding.letterheadUrl} alt="Letterhead" class="block h-auto w-full" />
  </div>

  <div id="export-body" class="grow p-24 pt-0 text-[12pt]">
    {#if qrDataUrl}
      <div class="absolute right-5 bottom-5 w-24">
        <img src={qrDataUrl} alt="QR" class="block h-24 w-24 p-0" />
      </div>
    {/if}

    <!-- Vertical Spacing to match PDF [0, 180, 0, 40] -->
    <div style="height: 1.5in;"></div>

    <header class="mb-12 text-center">
      <h1 class="text-[14pt] font-bold tracking-tight uppercase">Certificate of Full Payment</h1>
    </header>

    <div class="space-y-6" style="text-align: justify; line-height: 1.5;">
      <p>
        This is to certify that <strong>{clearanceData.name.toUpperCase()},</strong> a resident of
        the {activeBranding.hallName}, {activeBranding.campus}, has been cleared of any liability
        regarding association and water fees for the
        <strong>{translatePeriod(clearanceData.period)}.</strong>
      </p>

      <p>
        This certification is issued at the request of the aforementioned student for any legal
        purposes it may serve and without any obligation on the part of the Association or any of
        its Officers.
      </p>

      <p>
        Issued this {day} day of {month}
        {year} in the municipality of Los Baños, Laguna, Philippines.
      </p>
    </div>

    <!-- Signatory -->
    <div class="mt-24 mb-16 flex justify-end">
      <div class="text-center" style="min-width: 250px;">
        <p class="font-bold uppercase">{clearanceData.signatory}</p>
        <p class="text-[11pt]">{clearanceData.signatoryTitle}</p>
      </div>
    </div>
  </div>

  <div class="mt-auto px-24 pb-12 text-center text-[8pt]">
    <div>
      Reference Number: {clearanceData.refNo}
    </div>
    <p>This document is electronically generated and does not require a signature.</p>
    <div>
      Generated by HAOne on
      <span>
        {now.toLocaleString("en-US", {
          year: "numeric",
          month: "short",
          day: "numeric",
          hour: "numeric",
          minute: "2-digit",
          hour12: true
        })}.
      </span>
    </div>
  </div>
</div>

<style>
  #export-template {
    background-color: #ffffff !important;
    color: #000000 !important;
    font-family: "Archivo", sans-serif;
  }

  .export-font {
    font-family: "Archivo", sans-serif;
  }
</style>
