<script lang="ts">
  import { calculateTotal } from "$utils/math";
  import { formatCurrency, formatDate } from "$utils/formatters";
  import { parseRef } from "$utils/parsers";
  import { translateMop, translatePeriod } from "$utils/translators";
  import { brandingState } from "$state/branding.svelte";
  import { TransactionType, type ReceiptData } from "$lib/types";

  let { receiptData, qrDataUrl }: { receiptData: ReceiptData; qrDataUrl: string } = $props();

  const refInfo = $derived(parseRef(receiptData.referenceNumber));
  const activeBranding = $derived(brandingState.profile);
</script>

<div
  id="export-template"
  class="export-font fixed top-0 left-[-10000px] flex min-h-[297mm] w-[210mm] flex-col bg-[#ffffff] text-[#000000]"
>
  <!-- Letterhead -->
  <div class="w-full">
    <img src={activeBranding.letterheadUrl} alt="Letterhead" class="block h-auto w-full" />
  </div>

  <!-- Body Content -->
  <div id="export-body" class="grow p-24 pt-8 text-[12pt]">
    {#if qrDataUrl}
      <div class="absolute right-5 bottom-5 w-24">
        <img src={qrDataUrl} alt="QR" class="block h-24 w-24 p-0" />
      </div>
    {/if}
    <header class="relative mb-4 text-center text-[#000000]">
      <h1 class="text-md font-bold text-[#000000] uppercase">Acknowledgment Receipt</h1>
    </header>

    <div class="mb-8 w-full">
      {#each [["Issuer", activeBranding.issuerName], ["Date Issued", formatDate(receiptData.dateIssued)], ["Payment Date", formatDate(receiptData.paymentDate)], ["Payment Processor", translateMop(receiptData.processor)], ["Reference Number", refInfo.reference], ...(refInfo.invoice ? [["InstaPay Invoice No.", refInfo.invoice]] : []), ["Period", translatePeriod(receiptData.period)], ["Series Number", receiptData.seriesNumber], ["Received From", receiptData.receivedFrom.toUpperCase()], ["Received By", receiptData.receivedBy.toUpperCase()], ["Notes", receiptData.notes || ""]] as [label, val]}
        <div class="grid grid-cols-[200px_1fr] items-center">
          <div class="font-bold">
            {label}
          </div>
          <div class="">
            {val}
          </div>
        </div>
      {/each}
    </div>

    <table class="w-full border-collapse">
      <thead>
        <tr class="bg-[#f8fafc]">
          <th class="border-y border-[#000000] px-3 pb-4 text-left font-bold">Description</th>
          <th class="w-45 border-y border-[#000000] px-3 pb-4 text-right font-bold">Amount</th>
        </tr>
      </thead>
      <tbody>
        {#each receiptData.items as item}
          <tr>
            <td class="border-y border-[#000000] px-3 pb-4">
              {item.name}
              {#if item.amount < 0}
                <span class="ml-1 text-xs font-bold text-[#dc2626] uppercase">
                  ({receiptData.transactionType === TransactionType.RECLASSIFY
                    ? "Reclassified"
                    : "Refund"})
                </span>
              {/if}
            </td>
            <td class="border-y border-[#000000] px-3 pb-4 text-right tabular-nums"
              >{item.amount.toLocaleString("en-PH", { minimumFractionDigits: 2 })}</td
            >
          </tr>
        {/each}
        <tr class="bg-[#f8fafc]">
          <td class="border-y border-[#000000] px-3 pb-4 text-right font-bold">Total Amount</td>
          <td class="border-y border-[#000000] px-3 pb-4 text-right font-bold tabular-nums"
            >{formatCurrency(calculateTotal(receiptData.items))}</td
          >
        </tr>
      </tbody>
    </table>

    {#if receiptData.transactionType === TransactionType.WAIVED}
      <div class="mt-8 space-y-1 text-left text-[#000000]">
        <h4 class="font-bold italic">Acknowledgment of Waiver of Amount</h4>
        <p>
          The above-mentioned amount has been waived for all intents and purposes, and no further
          claims shall be made in this regard.
        </p>
      </div>
    {/if}
  </div>

  <!-- Footer -->
  <div class="mt-auto px-[1in] pb-12 text-center text-[8pt]">
    <p>
      This document is electronically generated, does not require a signature, and is not valid for
      claim of input tax.
    </p>
    <div>
      Generated by HAOne on
      <span>
        {new Date().toLocaleString("en-US", {
          year: "numeric",
          month: "short",
          day: "numeric",
          hour: "numeric",
          minute: "2-digit",
          hour12: true
        })}.
      </span>
    </div>
  </div>
</div>

<style>
  #export-template {
    background-color: #ffffff !important;
    color: #000000 !important;
    font-family: "Archivo", sans-serif;
  }

  .export-font {
    font-family: "Archivo", sans-serif;
  }
</style>
